// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwjtfobzvmnbcwaycjms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3anRmb2J6dm1uYmN3YXljam1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTg2NzAsImV4cCI6MjA1OTU3NDY3MH0.gJ3nmNxdEdITuKS4MRBU6Jb7a0j0grIFoRcqSipsSuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);